---
- name: Install Netdata
  hosts: all
  vars_files:
    - "../vars/main.yml"
  become: true
  become_method: sudo

  tasks:
  - name: Download the installation script
    get_url:
      url: https://my-netdata.io/kickstart.sh
      dest: ~/kickstart.sh
      mode: '0755'

  - name: Install Netdata without cloud connection
    command: ~/kickstart.sh --dont-wait --stable-channel --disable-telemetry --disable-cloud
    args:
      creates: /usr/sbin/netdata
    register: install_result

  - name: Cleanup installation script
    file:
      path: ~/kickstart.sh
      state: absent
